---

- name: Docker configuration
  copy:
    content: |
      {
          "exec-opts": ["native.cgroupdriver=systemd"],
          "bip": "192.168.99.1/24",
          "default-shm-size": "1G",
          "log-driver": "json-file",
          "log-opts": {
              "max-size": "100m",
              "max-file": "1"
          },
          "default-ulimits": {
              "memlock": {
                  "hard": -1,
                  "name": "memlock",
                  "soft": -1
              },
              "stack": {
                  "hard": 67108864,
                  "name": "stack",
                  "soft": 67108864
              }
          }
      }
    dest: /etc/docker/daemon.json
    mode: '0644'

- name: Add Kubernetes apt key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  register: add_repository_key

- name: Add Kubernetes repository
  apt_repository:
    repo: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
    state: present
    update_cache: true

- name: "Install Packages"
  apt:
    pkg:
    - kubeadm=1.18.0-00
    - kubelet=1.18.0-00
    - kubectl=1.18.0-00